version: '3.8'

services:
  cms:
    build: ./src
    command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    volumes:
      - ./src/:/usr/src/app/
    ports:
      - 8002:8000
    environment:
      - DATABASE_URL=postgresql://mylittledinkers:password@db/mylittledinkers
  db:
    image: postgres:15.1-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - 5432
    environment:
      - POSTGRES_USER=mylittledinkers
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=mylittledinkers

volumes:
  postgres_data: